const ERROR = {
    'NOT_FOUND': 404,
    'INTERNAL_ERROR': 500,
    'CONFLICT': 409,
    'EXPECTATION_FAILED': 417,
    'FORBIDDEN': 403,
    'UNAUTHORIZED': 401,
    'SERVICE_UNAVAILABLE': 503,
    'UNPROCESSABLE_ENTITY': 422
  };
  
  module.exports = {
    ERROR
  };
  